import { useState } from 'react'
import { supabase } from './supabaseClient'

export default function Auth() {
  const [isSignUp, setIsSignUp] = useState(true)
    const [email, setEmail] = useState('')
      const [password, setPassword] = useState('')
        const [username, setUsername] = useState('')
          const [loading, setLoading] = useState(false)
            const [message, setMessage] = useState('')

              const handleSubmit = async (e) => {
                  e.preventDefault()
                      setLoading(true)
                          setMessage('')

                              if (isSignUp) {
                                    const cleanUsername = username.trim()
                                          const { error } = await supabase.auth.signUp({
                                                  email: email.trim(),
                                                          password,
                                                                  options: {
                                                                            data: { username: cleanUsername, display_name: cleanUsername }
                                                                                    }
                                                                                          })
                                                                                                if (error) {
                                                                                                        setMessage('Erreur : ' + error.message)
                                                                                                              } else {
                                                                                                                      setMessage('Inscription réussie ! Vérifie ton email pour confirmer ton compte.')
                                                                                                                            }
                                                                                                                                } else {
                                                                                                                                      const { error } = await supabase.auth.signInWithPassword({
                                                                                                                                              email: email.trim(),
                                                                                                                                                      password
                                                                                                                                                            })
                                                                                                                                                                  if (error) {
                                                                                                                                                                          setMessage('Erreur : ' + error.message)
                                                                                                                                                                                }
                                                                                                                                                                                    }

                                                                                                                                                                                        setLoading(false)
                                                                                                                                                                                          }

                                                                                                                                                                                            return (
                                                                                                                                                                                                <div style={{ maxWidth: 400, margin: '50px auto', padding: 20 }}>
                                                                                                                                                                                                      <h1>P-Scalium Chat</h1>
                                                                                                                                                                                                            <h2>{isSignUp ? 'Inscription' : 'Connexion'}</h2>

                                                                                                                                                                                                                  <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                          {isSignUp && (
                                                                                                                                                                                                                                    <div style={{ marginBottom: 10 }}>
                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                            placeholder="Nom d'utilisateur"
                                                                                                                                                                                                                                                                                          value={username}
                                                                                                                                                                                                                                                                                                        onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                    style={{ width: '100%', padding: 8 }}
                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                          <div style={{ marginBottom: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Email"
                                                                                                                                                                                                                                                                                                                                                                                                                        value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '100%', padding: 8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginBottom: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Mot de passe"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        minLength={6}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ width: '100%', padding: 8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" disabled={loading} style={{ width: '100%', padding: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? 'Chargement...' : isSignUp ? "S'inscrire" : 'Se connecter'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {message && <p style={{ marginTop: 10 }}>{message}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ marginTop: 20, textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isSignUp ? 'Déjà un compte ?' : "Pas encore de compte ?"}{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setIsSignUp(!isSignUp)} style={{ background: 'none', border: 'none', color: 'blue', cursor: 'pointer' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isSignUp ? 'Se connecter' : "S'inscrire"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }