import { useState, useEffect } from 'react'
import { supabase } from './supabaseClient'

export default function ConversationList({ session: _session, onSelectConversation }) {
  const [conversations, setConversations] = useState([])
    const [searchUsername, setSearchUsername] = useState('')
      const [loading, setLoading] = useState(true)

        useEffect(() => {
            fetchConversations()
              }, [])

                const fetchConversations = async () => {
                    setLoading(true)

                        const { data: { user } } = await supabase.auth.getUser()

                            const { data: myParticipations, error: partError } = await supabase
                                  .from('conversation_participants')
                                        .select('conversation_id')
                                              .eq('user_id', user.id)

                                                  if (partError) {
                                                        alert('Erreur : ' + partError.message)
                                                              setLoading(false)
                                                                    return
                                                                        }

                                                                            const conversationIds = myParticipations.map((p) => p.conversation_id)

                                                                                if (conversationIds.length === 0) {
                                                                                      setConversations([])
                                                                                            setLoading(false)
                                                                                                  return
                                                                                                      }

                                                                                                          const { data: convData, error: convError } = await supabase
                                                                                                                .from('conversations')
                                                                                                                      .select('id, type, name, created_at')
                                                                                                                            .in('id', conversationIds)
                                                                                                                                  .order('created_at', { ascending: false })

                                                                                                                                      if (convError) {
                                                                                                                                            alert('Erreur : ' + convError.message)
                                                                                                                                                } else {
                                                                                                                                                      setConversations(convData)
                                                                                                                                                          }

                                                                                                                                                              setLoading(false)
                                                                                                                                                                }

                                                                                                                                                                  const startConversationWith = async () => {
                                                                                                                                                                      if (!searchUsername.trim()) return

                                                                                                                                                                          const { data: { user }, error: authError } = await supabase.auth.getUser()

                                                                                                                                                                              if (authError || !user) {
                                                                                                                                                                                    alert('Erreur auth : ' + (authError ? authError.message : 'utilisateur non trouvé'))
                                                                                                                                                                                          return
                                                                                                                                                                                              }

                                                                                                                                                                                                  const { data: targetUser, error: userError } = await supabase
                                                                                                                                                                                                        .from('profiles')
                                                                                                                                                                                                              .select('id, username')
                                                                                                                                                                                                                    .eq('username', searchUsername.trim())
                                                                                                                                                                                                                          .single()

                                                                                                                                                                                                                              if (userError) {
                                                                                                                                                                                                                                    alert('Erreur recherche : ' + userError.message)
                                                                                                                                                                                                                                          return
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                  if (!targetUser) {
                                                                                                                                                                                                                                                        alert('Utilisateur introuvable')
                                                                                                                                                                                                                                                              return
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                      if (targetUser.id === user.id) {
                                                                                                                                                                                                                                                                            alert('Tu ne peux pas démarrer une conversation avec toi-même')
                                                                                                                                                                                                                                                                                  return
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                          const { data: newConv, error: convError } = await supabase
                                                                                                                                                                                                                                                                                                .from('conversations')
                                                                                                                                                                                                                                                                                                      .insert({ type: 'direct', created_by: user.id })
                                                                                                                                                                                                                                                                                                            .select()
                                                                                                                                                                                                                                                                                                                  .single()

                                                                                                                                                                                                                                                                                                                      if (convError) {
                                                                                                                                                                                                                                                                                                                            alert('DETAILS COMPLETS: ' + JSON.stringify(convError, null, 2))
                                                                                                                                                                                                                                                                                                                                  return
                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                          const { error: partError } = await supabase.from('conversation_participants').insert([
                                                                                                                                                                                                                                                                                                                                                { conversation_id: newConv.id, user_id: user.id },
                                                                                                                                                                                                                                                                                                                                                      { conversation_id: newConv.id, user_id: targetUser.id }
                                                                                                                                                                                                                                                                                                                                                          ])

                                                                                                                                                                                                                                                                                                                                                              if (partError) {
                                                                                                                                                                                                                                                                                                                                                                    alert('Erreur participants : ' + partError.message)
                                                                                                                                                                                                                                                                                                                                                                          return
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                  setSearchUsername('')
                                                                                                                                                                                                                                                                                                                                                                                      fetchConversations()
                                                                                                                                                                                                                                                                                                                                                                                          onSelectConversation(newConv.id)
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ maxWidth: 500, margin: '0 auto', padding: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Mes conversations</h2>

                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Nom d'utilisateur..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={searchUsername}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setSearchUsername(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ flex: 1, padding: 8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={startConversationWith}>Nouvelle conversation</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Chargement...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : conversations.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Aucune conversation pour l'instant.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ul style={{ listStyle: 'none', padding: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {conversations.map((conv) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={conv.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => onSelectConversation(conv.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: '1px solid #ccc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: 'pointer'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {conv.name || (conv.type === 'direct' ? 'Conversation privée' : 'Groupe')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
